### ISSUE TITLE
Android: keyboard support

### ISSUE THREAD

**Issue by bit-garden** [godotengine/godot-proposals#12028]
### Tested versions

Android Godot Editor all versions

### System information

Android Editor

### Issue description

Android devices default keyboard does not support easy access to characters that are used for programming in general. 

Google Play Store has recently removed Hackers Keyboard from the play store. Without this app, it will be increasingly difficult to use Godot Editor on Android without installing an ad driven and likely untrustworthy keyboard. (This is not suggesting that installing 3rd party apps just to use another is acceptable in any case.)

I believe this should create a drive for an effort to implement an optional keyboard for mobile or touch screen driven devices to use to close the gap. 

### Steps to reproduce

Use the editor on Android. 

### Minimal reproduction project (MRP)

Android Godot Editor

**Comment by bit-garden** [comment]
> We are aware of this limitation. But creating a custom keyboard is not be an ideal solution, as it generally does not enhance the user experience. Users are typically more comfortable with their familiar keyboard layout.
> 
> A better approach would be to provide a panel containing frequently used characters that are not easily accessible on a standard virtual keyboard.

The counter to the point is that the available screen space is already extremely limited. 

Termux for example has a bar like this. But fitting unexpected keyboard sizes in with additional panels on an already tiny screen is not a good user experience anyways. 

I feel it's going to become a devil you know situation. 

![Image](https://github.com/user-attachments/assets/efe29852-2a1d-4fc6-8b15-f33b2bc601c1)

**Comment by baldierot** [comment]
> > We are aware of this limitation. But creating a custom keyboard is not be an ideal solution, as it generally does not enhance the user experience. Users are typically more comfortable with their familiar keyboard layout.
> > A better approach would be to provide a panel containing frequently used characters that are not easily accessible on a standard virtual keyboard.
> 
> The counter to the point is that the available screen space is already extremely limited.
> 
> Termux for example has a bar like this. But fitting unexpected keyboard sizes in with additional panels on an already tiny screen is not a good user experience either.
> 
> I feel it's going to become a devil you know situation.
> 
> ![Image](https://github.com/user-attachments/assets/efe29852-2a1d-4fc6-8b15-f33b2bc601c1)

If only Godot could work in portrait mode with the various UI panels being able to go fullscreen, or a tabbed interface. That would be something extraordinary.

**Comment by bit-garden** [comment]
This is a fantastic approach that solves a lot of the mobile UI issues with editing code and the node tree. I'm considering this resolved with [#105140](https://github.com/godotengine/godot/pull/105140)

**Comment by syntaxerror247** [comment]
Glad you liked the solution! I'm keeping this open to track the code editor enhancements -- we still plan to implement a separate solution for it. The coding symbols are still not accessible, so there's more work needed.
