### ISSUE TITLE
"Menu" key should open up the right click context menu for highlighted elements

### ISSUE THREAD

**Issue by greenfox1505** [godotengine/godot-proposals#143]
**Describe the project you are working on:** Writing GDScript within Godot

**Describe the problem or limitation you are having in your project:** The "Menu" key seems to be unused in the Godot Editor. Godot, like other text editors, should listen to the "Menu" key to right click context menus. This could be used for getting right-click menus from GDScript editor or even in the Scene tab. Other areas where a right-click triggers something and that area can be "highlighted" with arrow keys should also respond the the "Menu" key.

For those that don't know, the "Menu" key is a key on most keyboards (although some laptops require you use a "Fn" key to activate it). It usually exists between the Ctrl and Alt keys right of the space bar. It usually looks like a hamburger menu inside a box. https://en.wikipedia.org/wiki/Menu_key

**Describe how this feature / enhancement will help you overcome this problem or limitation:** This would allow you to open context menus with a keyboard. Does the exact same action as right clicking an object, but does not require context switching to a mouse.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:** No. I would use this enhancement will be used constantly.

**Comment by Calinou** [comment]
Support for the <kbd>Menu</kbd> key in LineEdit and TextEdit has been added in #29895. Is this complete enough, or does it still need to be implemented in other places?

**Comment by greenfox1505** [comment]
I will test Godot 3.2 Alpha 1 to see if that has everything I'm talking about here. But glancing at it, I think it only has the textedit version.

**Comment by Jummit** [comment]
I would also like this to be added. I think some places where it could show up is when selecting a node or a file, and in the code editor.

**Comment by greenfox1505** [comment]
In 3.2 Alpha1, looks like it works with the text editor but not the Scene tab or the FileSystem tab.

I would like this Menu key behavior to work across the board. Anywhere you can use arrows to select and object and a right click would open a menu, the menu key should also open that same menu.

**Comment by Calinou** [comment]
I'm not sure how context menus are defined in the code, so we may have to duplicate some code around to make it work everywhere :slightly_smiling_face:

**Comment by greenfox1505** [comment]
I notice another thing today. It is a feature request that is mostly dependent on Menu Key stuff working. But I think it should be a new request. (not really *dependent*, but it doesn't make sense until that works) 

Context Menus should have single key shortcut hints. For example, if you select some text in your browser and press "Menu" key (or right click) some letters are underlined. Those are short cuts. For example, this lets you press "Menu,Q" in Firefox to inspect something.

**Comment by Calinou** [comment]
> Context Menus should have single key shortcut hints. For example, if you select some text in your browser and press "Menu" key (or right click) some letters are underlined. Those are short cuts. For example, this lets you press "Menu,Q" in Firefox to inspect something.

For the record, this is being tracked in https://github.com/godotengine/godot-proposals/issues/1701.

**Comment by KoBeWi** [comment]
We could send a fake right-click event when pressing Menu key, to avoid code duplication.

**Comment by Sosasees** [comment]
@KoBeWi That sounds good.
In my mind, this "menu" key is basically just another way to right-click anyways.

**Comment by Calinou** [comment]
This was implemented in 4.0, closing.

```
❯ rg -i "\"ui_menu\"" 
scene/gui/line_edit.cpp
462:                    if (k->is_action("ui_menu", true)) {

scene/gui/text_edit.cpp
2166:           if (k->is_action("ui_menu", true)) {

scene/gui/rich_text_label.cpp
2124:                   if (k->is_action("ui_menu", true)) {

editor/plugins/text_editor.cpp
536:    if (k.is_valid() && k->is_pressed() && k->is_action("ui_menu", true)) {

editor/plugins/script_text_editor.cpp
1875:   } else if (k.is_valid() && k->is_action("ui_menu", true)) {

editor/plugins/text_shader_editor.cpp
998:    if (k.is_valid() && k->is_pressed() && k->is_action("ui_menu", true)) {

core/input/input_map.cpp
693:    default_builtin_cache.insert("ui_menu", inputs);
```

**Comment by Zireael07** [comment]
Why reopen? I thought it was fixed?

**Comment by Calinou** [comment]
> Why reopen? I thought it was fixed?

It's not implemented in editor-specific UI such as the Scene tree dock and FileSystem dock (when you have a node focused and press the <kbd>Menu</kbd> key).

**Comment by KoBeWi** [comment]
It seems to be implemented now (as of 4.5).

Any other place that's still missing it, and the button is applicable, should be considered a bug IMO.
