### ISSUE TITLE
AnimationPlayer moving slider has unclear behavior with changing/saving data on the scene file

### ISSUE THREAD

**Issue by securas** [godotengine/godot-proposals#2301]
### Describe the project you are working on
This is a generic issue that comes from using an animationplayer. I've uploaded a test project

### Describe the problem or limitation you are having in your project
When changing keys on an animation, the scene file tab shows (*) to indicate that the scene needs to be saved to store changes.
However, when moving the animation slider, even though it may alter the position of nodes or other properties, the scene file tab does not show (*) to indicate that the scene needs to be saved. In fact it is unclear if the scene file needs to be saved or not.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Have the editor acknowledge changed with the animation slider and add the (*) indicator to state that the changes need to be saved.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
This is an editor feature. It is unclear if it can be worked around.

### Is there a reason why this should be core and not an add-on in the asset library?
This is a core node of the editor.
[test_animation_player.zip](https://github.com/godotengine/godot-proposals/files/5992858/test_animation_player.zip)

**Comment by KoBeWi** [comment]
I think this is no longer relevant after RESET track was added.

**Comment by Calinou** [comment]
This was resolved by https://github.com/godotengine/godot/pull/43115, closing.

**Comment by securas** [comment]
#43115 does not solve this problem. This is not directly related to the reset track since the reset track is optional.

**Comment by securas** [comment]
> I think this is no longer relevant after RESET track was added.

Reset track is optional whereas this issue is not. So both points are not necessarily related.

**Comment by akien-mga** [comment]
I think what this describes is a bug, not a missing feature. The `(*)` marker is added automatically whenever the UndoRedo stack has changes registered, which *should be* whenever the scene changes. In this case the scene changes but not in an undo-able fashion and thus it's not marked as having changes, yet if you save it you will write some new data. So that's a bug.

Could you open a bug report on https://github.com/godotengine/godot/issues/ with the above info and reproduction project?

**Comment by securas** [comment]
Opened bug report: #46123
