### ISSUE TITLE
Open Project Manager with OpenGL3 renderer by default

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-proposals#4551]
### Describe the project you are working on

Godot's OpenGL renderer

### Describe the problem or limitation you are having in your project

Startup times are very slow in 4.0 right now, mostly due to the time to compile shaders or read shaders from cache. 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

This proposal would use the OpenGL3 renderer by default to benefit from quick startup times. The editor experience is identical between the Vulkan Backend and the OpenGL3 backend

Below are some measurements of startup time using Vulkan and OpenGL (both debug and release_debug) showing that the OpenGL3 backend consistently has faster startup times. 

```
hyperfine -i "./godot.linuxbsd.opt.tools.64.llvm --quit" "./godot.linuxbsd.opt.tools.64.llvm --rendering-driver opengl3 --quit" "./godot.linuxbsd.tools.64.llvm --quit" "./godot.linuxbsd.tools.64.llvm --rendering-driver opengl3 --quit"
Benchmark 1: ./godot.linuxbsd.opt.tools.64.llvm --quit
  Time (mean ± σ):     11.944 s ±  0.586 s    [User: 0.842 s, System: 0.290 s]
  Range (min … max):   10.736 s … 12.774 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Benchmark 2: ./godot.linuxbsd.opt.tools.64.llvm --rendering-driver opengl3 --quit
  Time (mean ± σ):      1.940 s ±  0.022 s    [User: 0.773 s, System: 0.164 s]
  Range (min … max):    1.905 s …  1.964 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Benchmark 3: ./godot.linuxbsd.tools.64.llvm --quit
  Time (mean ± σ):     13.081 s ±  0.317 s    [User: 1.934 s, System: 0.273 s]
  Range (min … max):   12.456 s … 13.507 s    10 runs
 
  Warning: Ignoring non-zero exit code.
 
Benchmark 4: ./godot.linuxbsd.tools.64.llvm --rendering-driver opengl3 --quit
  Time (mean ± σ):      2.754 s ±  0.310 s    [User: 1.759 s, System: 0.155 s]
  Range (min … max):    1.884 s …  2.938 s    10 runs
 
  Warning: Ignoring non-zero exit code.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Summary
  './godot.linuxbsd.opt.tools.64.llvm --rendering-driver opengl3 --quit' ran
    1.42 ± 0.16 times faster than './godot.linuxbsd.tools.64.llvm --rendering-driver opengl3 --quit'
    6.16 ± 0.31 times faster than './godot.linuxbsd.opt.tools.64.llvm --quit'
    6.74 ± 0.18 times faster than './godot.linuxbsd.tools.64.llvm --quit'
```

Outstanding concerns before this is implemented:
1. Clipping needs to be implemented before we do this so the project editor actually renders correctly (will have a PR for this tomorrow)
2. I am not sure whether the OpenGL backend works in both single window and multiwindow mode on OSX (maybe @bruvzg can weigh in?)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

We will just change the default from vulkan to opengl3 so that when no argument is passed, the OpenGL3 renderer is used.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The editor can be opened with the OpenGL3 backend by passing the ``--rendering-driver opengl3`` argument. But this would change the default for convenience. 

### Is there a reason why this should be core and not an add-on in the asset library?

This is the core engine

**Comment by aaronfranke** [comment]
It's probably better to default to Vulkan (via MoltenVK on Metal) on macOS for the project manager instead of using OpenGL, since OpenGL is deprecated on macOS. But I think this is a good idea on Windows and Linux (and BSD and maybe also Android and the web editor), so we can do OpenGL in the project manager everywhere but macOS.

**Comment by clayjohn** [comment]
@aaronfranke our plan for MacOS is to add ANGLEMetal and use that, so we shouldn't have to worry about compatibility there.

**Comment by bruvzg** [comment]
> I am not sure whether the OpenGL backend works in both single window and multiwindow mode on OSX (maybe @bruvzg can weigh in?)

Last time I have checked, macOS multi-window mode was working fine with OpenGL. But ANGLE (#54914) was not working at all, due to inability to compile shaders, which seems to be written for desktop OpenGL, not OpenGLES.

**Comment by clayjohn** [comment]
> Last time I have checked, macOS multi-window mode was working fine with OpenGL. But ANGLE (#54914) was not working at all, due to inability to compile shaders, which seems to be written for desktop OpenGL, not OpenGLES.

Sounds good. I recently updated the shaders so they would compile on WebGL (which also uses GLSL ES 300), so the problem with ANGLE should be fixed. We should look into properly integrating ANGLE soon (not just for MacOS, but for windows as well)

**Comment by bruvzg** [comment]
> so the problem with ANGLE should be fixed

Checked with the current `master`, upstream ANGLE and MetalANGLE, it's still failing:

```
     at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1317)
ERROR: GL ERROR: Source: OpenGL	Type: Error	ID: 1282	Severity: High	Message: Metal backend encountered an error. Code=1282.
   at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:181)
1:
ERROR: SceneShaderGLES3: Program linking failed:

   at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:216)
ERROR: Method/function failed.
   at: _compile_specialization (drivers/gles3/shader_gles3.cpp:364)
OpenGL Renderer: ANGLE (Metal Renderer: Apple M1)
WARNING: Cannot allocate mipmaps for canvas screen blur. Status: 36054
     at: _update_render_target (drivers/gles3/storage/texture_storage.cpp:1447)
ERROR: GL ERROR: Source: OpenGL	Type: Error	ID: 1282	Severity: High	Message: It is undefined behaviour to have a used but unbound uniform buffer.
   at: _gl_debug_print (drivers/gles3/rasterizer_gles3.cpp:181)
```

**Comment by Calinou** [comment]
I agree with the proposal. My only concern is whether we can still whether if Vulkan is supported when starting with the OpenGL renderer. This is largely why the project manager starts with GLES3 if supported on Godot 3.x – otherwise, we could always use GLES2 in the project manager there (it uses fewer resources).

**Comment by Zireael07** [comment]
I assume "we can still whether" should be "we can still **detect**", right?

**Comment by clayjohn** [comment]
Added already!
