### ISSUE TITLE
Add Pin Option in Theme Editor Tab

### ISSUE THREAD

**Issue by SparkT06** [godotengine/godot-proposals#7932]
### Describe the project you are working on

Description:

I am currently developing a game using the Godot engine and frequently need to access the theme editor. However, I find it inconvenient to have to click on the theme resource repeatedly. Unlike the animation tab, there is no option to pin the theme editor tab, which would allow for easier and more efficient access.

### Describe the problem or limitation you are having in your project

it inconvenient to have to click on the theme resource repeatedly. Unlike the animation tab, there is no option to pin the theme editor tab, which would allow for easier and more efficient access.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Proposal:

I propose the introduction of a pinning option in the theme editor tab, similar to the one available in the animation tab. This would allow developers to keep the theme editor tab open and easily accessible, reducing the need for repeated navigation to the theme resource.
Benefits:

Improved Workflow: The pinning option would streamline the development workflow by reducing the number of clicks required to access the theme editor.
Increased Efficiency: Developers would be able to work more efficiently by having instant access to the theme editor.
Better User Experience: The overall user experience of the Godot engine would be enhanced by making it more user-friendly and intuitive.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

<img width="325" alt="image" src="https://github.com/godotengine/godot-proposals/assets/118836956/003174c1-535a-42ff-a155-f6820a9c3834">

<img width="811" alt="image" src="https://github.com/godotengine/godot-proposals/assets/118836956/9a91ce8d-5401-486a-8ab7-1abecc848dd1">

### If this enhancement will not be used often, can it be worked around with a few lines of script?

implement the same pin option in Animation Editor tab to Theme editor tab

### Is there a reason why this should be core and not an add-on in the asset library?

it should be core as its is included in the editor

**Comment by KoBeWi** [comment]
The theme editor tends to hide more than it should and this is a bug, see https://github.com/godotengine/godot/issues/72271
It's going to be fixed soon.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/9218.

Is this still needed now that https://github.com/godotengine/godot/issues/72271 was fixed?

**Comment by KoBeWi** [comment]
The Theme Editor is "pinned" by default when editing a file and you need to close it manually, so this is resolved.

**Comment by Wartificer** [comment]
This is still happening to me in Godot v4.2.1 [b09f793f5]
As soon as I click a node, the Theme editor closes and I have to search the theme resource and open it up again.

**Comment by KoBeWi** [comment]
Theme editor is contextual. If you click unrelated Node (that doesn't contain the theme), it will be closed. What are you trying to do and why closing in this situation is unexpected?

btw you don't need to search for theme when you lose it, you can use the button for editing previous object:
![image](https://github.com/godotengine/godot-proposals/assets/2223172/99462b98-a7d2-4a34-9a85-ff96eb796b28)

**Comment by Wartificer** [comment]
> Theme editor is contextual. If you click unrelated Node (that doesn't contain the theme), it will be closed. What are you trying to do and why closing in this situation is unexpected?
> 
> btw you don't need to search for theme when you lose it, you can use the button for editing previous object: ![image](https://private-user-images.githubusercontent.com/2223172/322273728-99462b98-a7d2-4a34-9a85-ff96eb796b28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjQzNjAsIm5iZiI6MTcxMzU2NDA2MCwicGF0aCI6Ii8yMjIzMTcyLzMyMjI3MzcyOC05OTQ2MmI5OC1hN2QyLTRhMzQtOWE4NS1mZjk2ZWI3OTZiMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMjIwMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDBiMmEzOTY4MTY1YjNjNWU1NjQwMDdlZjBlOWZkMDYzNWY5NWRhZTUxM2Q2OGI2YzhlODUzOTljNWZkOGNmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.38HIf4PWSZ__5orAaNxCjjVjYHBb6vUXI7WQcll5Pjs)

When I work with Themes what I do is create a Theme or two, then I assign them on the highest Node possible. Then on subnodes or subscenes what I do is use Type Variations. I have to write the Type Variation on each special node for example, a button that is red I set it to 'ButtonFail' type variation. So whenever I click on a node like this and set the variation, the Theme Editor goes away completely, and usually whenever I'm setting UI nodes I also have to make changes in the Theme so this is extremely annoying.
I don't see why this menu needs to close considering others like Audio, Animation and Shader Editor that also use resources are there 100% of the time and are just tabs I can click (Which is what I want for the theme editor)

**Comment by Wartificer** [comment]
![image](https://github.com/godotengine/godot-proposals/assets/139187233/737ddace-af3b-4772-97a9-e63f33d17207)
In any case we should get something like this

**Comment by KoBeWi** [comment]
>  don't see why this menu needs to close considering others like Audio, Animation and Shader Editor that also use resources are there 100% of the time and are just tabs I can click

Audio and Shader Editor allow creating/loading resources, so you can edit something from within the editor. Animation is persistent, because you need to click different nodes to use it (but technically it can work like Theme editor now).

**Comment by Wartificer** [comment]
What I'm saying is still an issue though. The Theme Editor has no way of knowing if a node is affected by themes or not and just closes whenever you click any node. I need to have the theme editor open so I can see the list of variation type names to assign on nodes and/or make changes to the variation type after assigning it.
It comes down to convenience, even if it would be "correct" for the menu to close itself (which I think it's not) it still is just annoying to have to double click a resource or go to history every time after clicking a node.

**Comment by Jowan-Spooner** [comment]
Theme type variations are a really great and powerful addition to the theming workflow, unfortunately they are really annoying to work with because of this. I'm mainly working on very UI heavy projects like applications, plugins, etc. and the workflow usually is:
- Open the theme resource
- Navigate to a node I'd like to theme
    - Theme Editor closes
- Want to set the Theme type variation, forgot the exact name
- Open theme resource
    - Set theme type variation

If at any point you switch to a different scene, select a different node, just to check (e.g. what variation is set on another node): 
- Theme editor closes

I would understand this if another editor opened (like if I select an AnimationPlayer, but this happens all the time and is SUPER annoying. 

I guess the closing behaviour feels a little bit correct when opening a theme from the inspector, but not at all when opening it from the file system dock. That just feels really bad. Pinning would probably be a nice way to solve this.

I'm using 4.3 beta 2.

**Comment by KoBeWi** [comment]
If you set the Theme as project's default, the theme variations will be selectable from a dropdown list.

**Comment by Jowan-Spooner** [comment]
True, though that doesn't fix having to reopen the theme editor every other moment during styling.

**Comment by lexusinator** [comment]
It's true, while working with themes, you often have to move around in your project quite a lot, check that the theme plays well with your user interface elements, do adjustments, copy values, textures, style boxes around, etc... And using a theme for the whole project is the easiest way to ensure consistency. But it's annoying when the editor closes every time you switch contexts. So it would be great if the Theme editor would stay open, especially when using a default Theme.

**Comment by KoBeWi** [comment]
After https://github.com/godotengine/godot/pull/97543, the Theme editor persists until you Close it. You can test in in 4.4 dev3.
